name: Raise Market Products
run-name: Raise ${{ inputs.product }} by @${{ github.actor }}

on: 
  workflow_dispatch:
    inputs:
      product:
        description: 'github repository name (e.g. alfresco-connector) or blank for all projects of the axonivy-market org'
        required: false
      version:
        description: 'Snaphsot version to raise (e.g. "13.1.1-SNAPSHOT")'
        required: true
        default: '13.1.1-SNAPSHOT'
      engineUrl:
        description: 'Axon Ivy Engine URL'
        required: true
        default: 'https://developer.axonivy.com/permalink/13.1.1/axonivy-engine.zip'
      releaseBranch:
        description: 'Create a release branch to backup source code of the current version (e.g. "release/12.0"). This release branch should only be created for LTS versions.'
        required: true
        default: 'release/12.0'


jobs:
  raise-products:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          echo ${{ env.GH_TOKEN2 }} > token.sh
          gh auth login --with-token < token.sh
          gh auth setup-git
        env:
          GH_TOKEN2: ${{ secrets.GH }}

      - name: Raise Products
        run: |
          export engineUrl=${{ inputs.engineUrl }}
          export releaseBranch=${{ inputs.releaseBranch }}
          export IVY_JAVA_HOME=$JAVA_HOME_21_X64
          echo "workDir=$(pwd)" >> $GITHUB_ENV
          ./raise-all-market-products.sh ${{ inputs.version }} ${{ inputs.product }}
        shell: bash

      - name: Show migrated repositories
        if: ${{ inputs.product == '' }} 
        run: cat ${workDir}/migrated-repos.txt
        shell: bash
